// Portfolio videos — "Latest ads" folder first, then the category folders.
// Files: assets/videos (full), assets/videos/preview (6s muted loop), assets/posters.
const VIDEOS = [
  {id: "meena-film", title: "Meena Jewellers", cat: "Latest Ads", w: 1280, h: 720},
  {id: "rakshabandhan", title: "Raksha Bandhan", cat: "Latest Ads", w: 1280, h: 720},
  {id: "dairy-milk", title: "Dairy Milk", cat: "Latest Ads", w: 1280, h: 720},
  {id: "chicken-popcorn-reel", title: "Chicken Popcorn", cat: "Latest Ads", w: 1280, h: 720},
  {id: "latest-03", title: "Bridal Necklace", cat: "Latest Ads", w: 720, h: 1280},
  {id: "latest-01", title: "Emerald Drop", cat: "Latest Ads", w: 720, h: 1280},
  {id: "svarn-reel", title: "Summer Edit", cat: "Latest Ads", w: 720, h: 1280},
  {id: "latest-02", title: "Svarn — Links", cat: "Latest Ads", w: 720, h: 1280},
  {id: "latest-05", title: "Svarn — Bracelet", cat: "Latest Ads", w: 720, h: 1280},
  {id: "latest-04", title: "Svarn — Necklace", cat: "Latest Ads", w: 720, h: 1280},
  {id: "adidas", title: "Adidas", cat: "Insta Reels", w: 720, h: 1280},
  {id: "pepsi", title: "Pepsi", cat: "Insta Reels", w: 720, h: 1280},
  {id: "kfc", title: "KFC", cat: "Insta Reels", w: 720, h: 1280},
  {id: "maggi", title: "Maggi", cat: "Insta Reels", w: 720, h: 1280},
  {id: "pringles", title: "Pringles", cat: "Insta Reels", w: 720, h: 1280},
  {id: "hm", title: "H&M", cat: "Insta Reels", w: 720, h: 1280},
  {id: "dubai-chocolate", title: "Dubai Chocolate", cat: "Insta Reels", w: 720, h: 1280},
  {id: "pilgrim-serum", title: "Pilgrim Serum", cat: "Insta Reels", w: 720, h: 1280},
  {id: "ace-captions", title: "Ace Plant Protein", cat: "Insta Reels", w: 720, h: 1280},
  {id: "pain-relief", title: "Pain Relief", cat: "Insta Reels", w: 720, h: 1280},
  {id: "upnourish", title: "Upnourish", cat: "UGC", w: 720, h: 1280},
  {id: "tangy-lemon", title: "Tangy Lemon", cat: "UGC", w: 720, h: 1280},
  {id: "meena-jewellers", title: "Meena Jewellers — Scope Cut", cat: "Jewellery", w: 1280, h: 546},
  {id: "svarn-independence", title: "Svarn — Independence Day", cat: "Jewellery", w: 1280, h: 720},
  {id: "svarn-2", title: "Svarn — Make it Golden", cat: "Jewellery", w: 720, h: 1280},
  {id: "svarn-3", title: "Svarn — Little Joys", cat: "Jewellery", w: 720, h: 1280},
  {id: "svarn-1", title: "Svarn — Heritage", cat: "Jewellery", w: 848, h: 478},
  {id: "jewellery-reel", title: "Svarn — Necklace Reel", cat: "Jewellery", w: 720, h: 1280},
  {id: "japanese-style", title: "Japanese Style", cat: "Jewellery", w: 1280, h: 720},
  {id: "naam", title: "Naam", cat: "Lifestyle", w: 1280, h: 720},
  {id: "prada", title: "Prada", cat: "Lifestyle", w: 1280, h: 720},
  {id: "ritu-kumar", title: "Ritu Kumar", cat: "Lifestyle", w: 1280, h: 720},
  {id: "luxury", title: "Luxury Spa", cat: "Lifestyle", w: 1280, h: 720},
  {id: "super-you", title: "Super You", cat: "Lifestyle", w: 1280, h: 720},
  {id: "amul", title: "Amul Milk", cat: "Lifestyle", w: 1280, h: 720},
  {id: "dabur", title: "Dabur", cat: "TV Commercial", w: 1280, h: 720},
  {id: "chicken-popcorn", title: "Chicken Popcorn — TV Spot", cat: "TV Commercial", w: 1280, h: 720},
  {id: "hatti-butti", title: "Hatti Butti", cat: "Local Business", w: 1280, h: 720},
  {id: "olympic", title: "Olympic", cat: "Local Business", w: 1280, h: 720},
  {id: "fonfox", title: "Fonfox", cat: "Local Business", w: 1280, h: 720},
  {id: "bio-tech", title: "Bio Tech", cat: "Local Business", w: 1280, h: 720},
  {id: "toss", title: "Toss", cat: "Local Business", w: 848, h: 478},
  {id: "emaar", title: "Emaar", cat: "Real Estate", w: 1280, h: 720},
  {id: "real-estate-1", title: "Villa Walkthrough", cat: "Real Estate", w: 1280, h: 720},
  {id: "real-estate-2", title: "Aerial Reveal", cat: "Real Estate", w: 1280, h: 720},
  {id: "real-estate-3", title: "Rising Tower", cat: "Real Estate", w: 1280, h: 720},
  {id: "korean-love-story", title: "Korean Love Story", cat: "Story Ads", w: 1280, h: 720},
  {id: "kirloskar", title: "Kirloskar", cat: "Story Ads", w: 720, h: 1280},
];
